# Generated by Django 2.2.19 on 2022-03-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220311_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pub_date',
        ),
    ]
